### ISSUE TITLE
Fulfillment Inbound 2024-03-20:  Inbound Plan Getting Immediately Voided  

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#4046] opened 2024-07-24 16:09 UTC
As of today, immediately after creating an inbound plan, the plan gets voided.  Any subsequent attempts to continue the workflow fail because the plan is voided.  
  1.  CreateInboundPlan:  Succeeds
  2.  GeneratePackingOptions:  Fails with error:
  ```
     {
      "errors": [
        {
          "code": "BadRequest",
          "message": "ERROR: Operation GeneratePackingOptions can not be processed on a cancelled inbound plan.",
          "details": ""
        }
      ]
    }
```
  4.  ListInboundPlans indicates the plan was created at 2024-07-24T15:59:27 and voided 5s later 2024-07-24T15:59:32
  ```
     {
      "createdAt": "2024-07-24T15:59:27Z",
      "marketplaceIds": [
          "ATVPDKIKX0DER"
      ],
      "sourceAddress": {
          "phoneNumber": "555-555-1234",
          "city": "Tampa",
          "countryCode": "US",
          "postalCode": "33605",
          "companyName": "XXXXX",
          "name": "Sam Iam",
          "addressLine1": "1601 Main St",
          "stateOrProvinceCode": "FL"
      },
      "lastUpdatedAt": "2024-07-24T15:59:32Z",
      "name": "Plan1",
      "inboundPlanId": "wffc3ef963-9be4-4ddc-bcba-cd1a41eec6d7",
      "status": "VOIDED"
  }
```

**Comment by jamespclay** [comment] 2024-07-25 16:11
We are also experiencing this issue. Shipment plans are created successfully using the API, only to be cancelled immediately when they are opened to be worked in Seller Central.

**Comment by brandondev1** [comment] 2024-07-25 18:59
After calling GeneratePackingOptions and then GetOperationStatus, prior to ListPackingOptions, I get this message:
```
{
  "operationStatus": "FAILED",
  "operationId": "801106e9-6ab9-4f7e-bf4f-0f1912ff6be0",
  "operation": "generatePackingOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Operation GeneratePackingOptions cannot be processed because the inbound plan does not support packing options."
    }
  ]
}
```

**Comment by blairanderson** [comment] 2024-07-26 20:54
Same exact thing with me. 

create plan = successful 
get_operation = forbidden
GET inboundPlans/{inbound_plan_id} 

status: VOIDED

**Comment by puppsupr** [comment] 2024-07-29 20:03
Hi,
Can you please provide the inboundPlanIds where you see these cancellations !

**Comment by brandondev1** [comment] 2024-07-29 20:07
> Hi, Can you please provide the inboundPlanIds where you see these cancellations !

An example inboundPlanId is in the response from ListInboundPlan in my original post:  wffc3ef963-9be4-4ddc-bcba-cd1a41eec6d7
FYI, I have not seen this issue today, but was seeing it all last week.

**Comment by puppsupr** [comment] 2024-07-29 20:53
Hi [brandondev1](https://github.com/brandondev1),
Please let me know if you see it again this week.

**Comment by blairanderson** [comment] 2024-07-30 01:41
@puppsupr 

- wf2b148ea3-828e-4689-8493-7da1d63974db
- wfc7694b7a-df89-41ce-b31a-1138ef04d023
- wfdf6d4a7e-da3b-4dae-849a-20b1c5876345

**Comment by blairanderson** [comment] 2024-07-31 21:12
@puppsupr @brandondev1  here is another today: 

```json
{
  "createdAt": "2024-07-31T21:09:33Z",
  "marketplaceIds": [
    "ATVPDKIKX0DER"
  ],
  "packingOptions": [

  ],
  "sourceAddress": {
    "phoneNumber": "8059270140",
    "city": "Cambria",
    "countryCode": "US",
    "postalCode": "93428",
    "companyName": "PlumbRite MFG",
    "name": "PlumbRite MFG",
    "addressLine1": "2419 Village Ln",
    "stateOrProvinceCode": "CA",
    "email": "slater-supply@m.shipmentbot.com"
  },
  "lastUpdatedAt": "2024-07-31T21:09:40Z",
  "name": "2024-07-31_WINGTITE-REPLACEMENT_24",
  "inboundPlanId": "wf99a84398-1d71-4442-af4d-ad440edcb2b9",
  "placementOptions": [

  ],
  "shipments": [

  ],
  "status": "VOIDED"
}
```

Created and updated within 7-milliseconds.

**Comment by puppsupr** [comment] 2024-08-06 03:15
Thanks ! Checking with Product team on this.

**Comment by blairanderson** [comment] 2024-08-06 21:19
@puppsupr 

here is another from today: "wf100a772f-1497-4f63-9a2f-61d629f8c3cc"

**Comment by puppsupr** [comment] 2024-08-09 18:08
Hi,
This is happening because the CreateInboundPlan input has prep and label owners both set to NONE. Provide the appropriate prep and labelling owner inputs in the CreateInboundPlanRequest.

**Comment by blairanderson** [comment] 2024-08-10 17:49
hi @puppsupr - when we input "SELLER" OR "AMAZON" we get these errors: 

```json
"errors": [
{
"code": "BadRequest",
"message": "ERROR: OURSKU does not require labelOwner but SELLER was assigned. Accepted values: [NONE]",
},
{
"code": "BadRequest",
"message": "ERROR: OURSKU does not require prepOwner but SELLER was assigned. Accepted values: [NONE]"
}
```

**Comment by blairanderson** [comment] 2024-08-14 15:45
hi @puppsupr 

anoother plan immediately voided: wf4f8e0b25-a665-4239-a17e-9c43b516528d


<br class="Apple-interchange-newline">

**Comment by jackmin-sw** [comment] 2024-08-17 03:08
@puppsupr I got the same error,  the plan immediately voided: wfe11154a5-7fb0-4513-9e06-a5d240fcf60a
when I set prepOwner it said it should be NONE，
   "labelOwner": "SELLER",
    "prepOwner": "NONE",
 so I change it to NONE, then I create the plan, but when I call the api to generate packiing options ,it response "ERROR: Operation GeneratePackingOptions can not be processed on a cancelled inbound plan."

**Comment by puppsupr** [comment] 2024-08-20 17:44
Hi [blairanderson](https://github.com/blairanderson) and [jackmin-sw](https://github.com/jackmin-sw), Can you please provide complete request and response for createInboundPlan, Operation Status and the generatepackingOptions calls.

**Comment by blairanderson** [comment] 2024-08-26 17:41
request:
```request
POST /inbound/fba/2024-03-20/inboundPlans HTTP/1.1
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: application/json
User-Agent: Ruby
Host: sellingpartnerapi-na.amazon.com
X-Amz-Access-Token: [API_TOKEN_REMOVED]
Content-Type: application/json
Connection: close
Content-Length: 371

{
  "destinationMarketplaces": ["ATVPDKIKX0DER"],
  "items": [
    {
      "msku": "MYSKU",
      "quantity": "24",
      "prepOwner": "NONE",
      "labelOwner": "NONE"
    }
  ],
  "name": "2024-08-26_24_MYSKU",
  "sourceAddress": {
    "phoneNumber": "12345123",
    "city": "Cambria",
    "countryCode": "US",
    "postalCode": "12345",
    "name": "Something MFG",
    "addressLine1": "1234 address",
    "stateOrProvinceCode": "CA"
  }
}
```
response: 
```response
HTTP/1.1 202 
Server: Server
Date: Mon, 26 Aug 2024 17:13:31 GMT
Content-Type: application/json
Content-Length: 111
Connection: close
x-amz-rid: E3P1C3H3KA0RFFTQ6ZA6
x-amzn-RateLimit-Limit: 2.0
x-amzn-RequestId: bbfcf60b-3b5c-4847-8b79-bbb07f39d122
x-amz-apigw-id: OPFbbfcf60b3b5c
X-Amzn-Trace-Id: Root=1-66ccb7bb-bbfcf60b3b5c4847
Vary: Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload

{
  "operationId": "a4ed1f47-8698-487c-953e-964c150e9d14",
  "inboundPlanId": "wff9fe9efa-c507-4cfb-baea-139b9a93dfb5"
}
```

**Comment by blairanderson** [comment] 2024-08-26 18:12
@puppsupr I found the error was `FBA_INB_0182`

**Comment by blairanderson** [comment] 2024-08-26 18:14
https://github.com/amzn/selling-partner-api-samples/issues/52

1. visit sellercentral -> shipments
2. click "send to amazon"
3. find your items 
4. click "updated prep instructions"
5. click "restart prep instructions"
6. set the prep category -> save

You should now be able to create the shipment.

**Comment by johnkw** [comment] 2024-08-27 01:28
This appears to be a duplicate of bug #556.

**Comment by puppsupr** [comment] 2024-08-28 05:00
FBA Tech Team was able to review and identified that this was happening due to error as pointed out by [blairanderson](https://github.com/blairanderson) Prep classification for this SKU was missing. Choose the prep category that applies to this SKU and apply any required prep and labeling to each sellable unit.

Team is working on fixing handling the errors to show upfront in this case. To resolve thie provide the appropriate prep and labelling owner inputs in the CreateInboundPlanRequest

**Comment by denbondd** [comment] 2024-08-28 11:59
@puppsupr is FBA Tech Team going to implement an endpoint to set prep and labeling through API? Manual work on their website becomes an issue for 7000 products... And if yes, any timeline on that?

**Comment by johnkw** [comment] 2024-08-28 16:07
As per bug #556 the current working API is marked deprecated.  Do we have an ETA for this part of the new API being implemented, or an answer on what happens if the new API is not fully implemented by December?

Is the December removal of the current working API going to proceed even if the new API is not yet fully implemented by then?

**Comment by puppsupr** [comment] 2024-08-28 16:53
> @puppsupr is FBA Tech Team going to implement an endpoint to set prep and labeling through API? Manual work on their website becomes an issue for 7000 products... And if yes, any timeline on that?

Hi [denbondd](https://github.com/denbondd), yes its in progress and provide more updates soon !

**Comment by puppsupr** [comment] 2024-08-28 16:55
> As per bug #556 the current working API is marked deprecated. Do we have an ETA for this part of the new API being implemented, or an answer on what happens if the new API is not fully implemented by December?
> 
> Is the December removal of the current working API going to proceed even if the new API is not yet fully implemented by then?

It will be released very soon. Should not be a blocker for migration.

**Closed** 2024-09-11 05:41 UTC
Labels: bug, closing soon

**Comment by chuckchill** [comment] 2024-09-27 06:50
Hi @puppsupr  ,Has this question fixed?? I still get the error

**Comment by chuckchill** [comment] 2024-09-27 06:57
Hi @puppsupr ,Has this error fixed?? I still get the error

**Comment by manikandan26** [comment] 2024-09-30 07:27
> Hi @puppsupr ,Has this error fixed?? I still get the error

It looks like this issue was not fixed, I also got the VOIDED status immediately after creating InboundPlan,
Has anyone found the fixes?

**Comment by blairanderson** [comment] 2024-09-30 17:00
hi @manikandan26 @chuckchill you need to log into sellercentral and make sure the SKUs have their prep categories selected. 

https://github.com/amzn/selling-partner-api-models/issues/4046#issuecomment-2310787910

**Comment by Waqas770** [comment] 2024-10-30 10:24
Can someone help me to understand the flow ...
I have the shipment showing in the V0 version 

6 => array:7 [▼
    "ShipmentId" => "ABCDEFGHI"
    "ShipmentName" => "FBA STA (10/28/2024 19:24)-HGR6"
    "ShipFromAddress" => array:6 [▶]
    "DestinationFulfillmentCenterId" => "HGR6"
    "ShipmentStatus" => "RECEIVING"
    "LabelPrepType" => "SELLER_LABEL"
    "BoxContentsSource" => "INTERACTIVE"
  ]
  
  In the New version **(Fulfillment Inbound API v2024-03-20)**
  But when I call the list **listInboundPlans**
  so the list of bound plans in response 
  But no shipment when calling the **getInboundPlan(inboundPlanId)**
  
  
  How this inboundplans and shipments works in this new version
  need urgent response

**Comment by johnkw** [comment] 2024-10-30 20:05
See https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide -- it has everything except for the prep step. The doc still needs to be fixed for that part.

**Comment by puppsupr** [comment] 2024-10-31 20:28
Hi @johnkw,
Here is the updated information [Retrieve preparation instructions for an MSKU](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#retrieve-preparation-instructions-for-an-msku).

**Comment by puppsupr** [comment] 2024-10-31 20:30
> Can someone help me to understand the flow ... I have the shipment showing in the V0 version
> 
> 6 => array:7 [▼ "ShipmentId" => "ABCDEFGHI" "ShipmentName" => "FBA STA (10/28/2024 19:24)-HGR6" "ShipFromAddress" => array:6 [▶] "DestinationFulfillmentCenterId" => "HGR6" "ShipmentStatus" => "RECEIVING" "LabelPrepType" => "SELLER_LABEL" "BoxContentsSource" => "INTERACTIVE" ]
> 
> In the New version **(Fulfillment Inbound API v2024-03-20)** But when I call the list **listInboundPlans** so the list of bound plans in response But no shipment when calling the **getInboundPlan(inboundPlanId)**
> 
> How this inboundplans and shipments works in this new version need urgent response

Hi, please check out the [Fulfillment Inbound shipment workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow). Also we have the [Postman Collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) for all the use-cases and also [sample codes](https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound) to understand and test the flow.

**Comment by johnkw** [comment] 2024-11-01 00:36
> Hi @johnkw, Here is the updated information [Retrieve preparation instructions for an MSKU](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#retrieve-preparation-instructions-for-an-msku).

Ok... some progress thanks.  Why is it way down at the bottom, when it's the first thing you must do, and it blocks all of the other steps?

Also it should be in the graphic at the top, for the same reason.

**Comment by puppsupr** [comment] 2024-11-01 01:30
Thanks for the feedback. Will try to improve it.

**Comment by johnkw** [comment] 2024-11-01 02:04
Thanks for communicating on these issues here on github. It's so much more useful to have a consolidated place where everyone can collaborate on understanding these API bugs and usecase oddities.
