### ISSUE TITLE
The ‘readyToShipWindow’ field in the generateTransportationOptions interface is not effective after being entered.

### ISSUE THREAD

**Issue by ccyun06** [amzn/selling-partner-api-models#4102] opened 2024-08-19 06:34 UTC
The ‘readyToShipWindow’ field in the generateTransportationOptions interface is not effective after being entered.
No matter what date I input, the backend UI always displays the current date.
The “listDeliveryWindowOptions” interface always returns a list of time slots starting from the creation date for a period of 44 days.

generateTransportationOptions API request example:
{
    "placementOptionId": "{{placementOptionId}}",
    "shipmentTransportationConfigurations": [
        {
            "contactInformation": {
                "email": "email@email.com",
                "name": "John Smithy",
                "phoneNumber": "1234567890"
            },
            "freightInformation": {
                "declaredValue": {
                    "amount": 2000,
                    "code": "USD"
                },
                "freightClass": "FC_50"
            },
            "pallets": [
                {
                    "dimensions": {
                        "height": 50,
                        "length": 40,
                        "unitOfMeasurement": "CM",
                        "width": 40
                    },
                    "quantity": 3,
                    "stackability": "NON_STACKABLE",
                    "weight": {
                        "unit": "KG",
                        "value": 800
                    }
                }
            ],
            "readyToShipWindow": {
                "start": "2024-08-25T00:00Z"
            },
            "shipmentId": "{{shipmentId}}"
        }
    ]
}

**Comment by Christin519** [comment] 2024-08-19 06:52
Me too

**Comment by emakunin** [comment] 2024-09-03 08:57
This request is a duplicate of https://github.com/amzn/selling-partner-api-models/issues/4048 it seems.

**Comment by Christin519** [comment] 2024-09-03 09:16
> This request is a duplicate of #4048 it seems.

No!   Our shipments to Amazon usually take 60 days or more, but the delivery window returned by the interface is up to 45 days.

**Comment by emakunin** [comment] 2024-09-03 10:08
oh you are right, my bad it's another problem .I'll update

**Comment by Christin519** [comment] 2024-09-04 02:02
> oh you are right, my bad it's another problem .I'll update

Thanks.So, can you take a look at this problem and give a solution?It's very important to me. 45 days is not enough to ship from my country to Amazon(US)

**Comment by emakunin** [comment] 2024-09-04 08:09
I would be glad to, but we are on the same boat. I'm not an amazon SDE :P

**Comment by ccyun06** [comment] 2024-09-05 03:37
@mafge Could you please take a look at this problem for me?

**Comment by puppsupr** [comment] 2024-09-11 06:16
Checking with team on this !

**Comment by Christin519** [comment] 2024-09-12 01:39
> Checking with team on this !

Thank you, we are always waiting for your result.😊

**Comment by Christin519** [comment] 2024-09-18 06:40
> Checking with team on this !

@puppsupr Is there a conclusion now?

**Comment by Christin519** [comment] 2024-09-24 02:08
@puppsupr Hello？

**Comment by puppsupr** [comment] 2024-09-30 21:35
Hi Sorry for the delay,
Your shipment must arrive within 45 days of shipment creation for domestic, and 75 days for international. That is why you can't input more than 45 days and it's defaulting back. https://sellercentral.amazon.com/help/hub/reference/external/GL5XA3MNXAJKJE8E

**Closed** 2024-10-03 22:11 UTC
Labels: closing soon, answer in docs

**Comment by Christin519** [comment] 2024-10-11 06:00
> Hi Sorry for the delay, Your shipment must arrive within 45 days of shipment creation for domestic, and 75 days for international. That is why you can't input more than 45 days and it's defaulting back. https://sellercentral.amazon.com/help/hub/reference/external/GL5XA3MNXAJKJE8E

but my shipment is international,  I can only choose 45 days.
My shipment is sent from Asia.
```
"sourceAddress": {
                "addressLine1": "xxx",
                "city": "fuzhou",
                "countryCode": "CN",
                "name": "topshoesUS",
                "phoneNumber": "123456",
                "postalCode": "350000",
                "stateOrProvinceCode": "Fujian"
        }
```

**Comment by Christin519** [comment] 2024-10-24 02:44
@puppsupr Hello？

**Comment by puppsupr** [comment] 2024-10-24 18:40
Hi @Christin519,
Please provide your full request and responses along with the inbound plan id.

**Comment by Christin519** [comment] 2024-10-25 02:04
> Hi @Christin519, Please provide your full request and responses along with the inbound plan id.

OK, This is all my requests and responses about this inbound plan.

My problem is that my source address is China and the goods are shipped to the US, but in the step of **generating the delivery window**, I can only get a maximum delivery period of **45** days. This is contrary to the information I learned before, which was that international shipments can have a period of **75** days or even **90** days.

So I want to know how Amazon determines whether a shipment is an international shipment. This is very important to me. It is difficult for me to guarantee that all shipments can arrive in the US from China within 45 days.

I hope you can solve my problem. This is very important to me. Thank you very much!!!!!!

inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb

I omitted the response of **getInboundOperationStatus**, and I can ensure that it is all successful

**createInboundPlan** request
```
{
        "destinationMarketplaces": ["ATVPDKIKX0DER"],
        "items": [{
                "msku": "160912-W-NEW-BLACK DK.GREY-SZ-07",
                "quantity": 6,
                "labelOwner": "SELLER",
                "prepOwner": "NONE"
        }], 
        "sourceAddress": {
                "addressLine1": "xxx",
                "city": "fuzhou",
                "countryCode": "CN",
                "name": "topshoesUS",
                "phoneNumber": "123456",
                "postalCode": "350000",
                "stateOrProvinceCode": "Fujian"
        }
}
```
**createInboundPlan** response
`{"operationId":"e268a782-30b2-4d19-9811-20b02b2601f4","inboundPlanId":"wf60ced554-79c3-4b7c-a0a9-a93808d2aedb"}`

**generatePlacementOptions** request 
inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb

**generatePlacementOptions** response:
`{"operationId":"70cd89c1-68a0-427f-8df3-7f9c309bef75"}
`

**listPlacementOptions** request:
inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb

**listPlacementOptions** response:
```
{
	"pagination": {},
	"placementOptions": [{
		"fees": [{
			"description": "Placement service fee represents service to inbound with minimal shipment splits and destinations of skus",
			"type": "FEE",
			"value": {
				"amount": 1.86,
				"code": "USD"
			},
			"target": "Placement Services"
		}],
		"shipmentIds": ["sh058aedb1-65d5-41d0-9b82-258678e2e342", "sh7dd5e18c-99bf-4089-b3c3-b3364c0fabdf"],
		"discounts": [],
		"expiration": "2024-10-28T01:18:05.311Z",
		"placementOptionId": "pl206332ed-8b3a-49b9-9c01-084da28fc592",
		"status": "OFFERED"
	}, {
		"fees": [{
			"description": "Placement service fee represents service to inbound with minimal shipment splits and destinations of skus",
			"type": "FEE",
			"value": {
				"amount": 1.62,
				"code": "USD"
			},
			"target": "Placement Services"
		}],
		"shipmentIds": ["sh88defd94-9376-4b30-bc3d-dc8e1526baad"],
		"discounts": [],
		"expiration": "2024-10-28T01:18:05.311Z",
		"placementOptionId": "pl600dbd9b-9735-43ff-9481-bfeb4b1792bf",
		"status": "OFFERED"
	}, {
		"fees": [{
			"description": "Placement service fee represents service to inbound with minimal shipment splits and destinations of skus",
			"type": "FEE",
			"value": {
				"amount": 1.44,
				"code": "USD"
			},
			"target": "Placement Services"
		}],
		"shipmentIds": ["sh57998bc7-cfa8-4e7b-98ba-519854941bd4", "sh5dd98484-763a-48e3-b47e-c572de819bef"],
		"discounts": [],
		"expiration": "2024-10-28T01:18:05.311Z",
		"placementOptionId": "pla6c9266c-cae2-4cec-a0ba-769ff5af37cd",
		"status": "OFFERED"
	}]
}
```

**confirmPlacementOption**  request
inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb
placementOptionId: pl600dbd9b-9735-43ff-9481-bfeb4b1792bf

**confirmPlacementOption** response
`{"operationId":"75c37407-273c-4e0c-912f-071526304872"}
`

**generateTransportationOptions** request
```
{
	"inboundPlanId": "wf60ced554-79c3-4b7c-a0a9-a93808d2aedb",
	"placementOptionId": "pl600dbd9b-9735-43ff-9481-bfeb4b1792bf",
	"shipmentTransportationConfigurations": [{
		"readyToShipWindow": {
			"start": "2024-10-30T00:00Z"
		},
		"shipmentId": "sh88defd94-9376-4b30-bc3d-dc8e1526baad"
	}]
}
```
**generateTransportationOptions** response
`{"operationId":"36f4f539-a36a-4551-90f3-7099910376f8"}
`

**generateDeliveryWindowOptions** request
inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb
shipmentId: sh88defd94-9376-4b30-bc3d-dc8e1526baad

**generateDeliveryWindowOptions** response
`{"operationId":"08418e38-1825-4d69-9a8a-114f0d97c4d9"}
`

**listDeliveryWindowOptions**  request
inboundPlanId: wf60ced554-79c3-4b7c-a0a9-a93808d2aedb
placementOptionId: pl600dbd9b-9735-43ff-9481-bfeb4b1792bf
shipmentId: sh88defd94-9376-4b30-bc3d-dc8e1526baad
pageSize: 100

**listDeliveryWindowOptions**  response
```
{
	"pagination": {},
	"deliveryWindowOptions": [{
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-01T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwde946c4f-b16f-4422-8ad0-e5da4e5697bf",
		"startDate": "2024-10-25T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-02T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw165ff483-2bf9-4fd8-82eb-a67ced0beac5",
		"startDate": "2024-10-26T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-03T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw56bbb6ed-57c6-4f80-89aa-33eac55a2d4c",
		"startDate": "2024-10-27T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-04T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw50b58008-f550-4c63-8b02-e263bb3b299e",
		"startDate": "2024-10-28T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-05T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwf165c8d7-3fa7-4964-a6d1-616ea0fbb515",
		"startDate": "2024-10-29T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-06T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwaa3833f0-c9a8-49df-acaa-2c8ea069132a",
		"startDate": "2024-10-30T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-07T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw90300f1a-8d37-4ce9-8511-64fc6704f66c",
		"startDate": "2024-10-31T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-08T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwa1b3d7c7-7002-42d3-bc3c-2b55fe109c20",
		"startDate": "2024-11-01T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-09T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw8ccfa1d5-4d25-406d-b21f-7e1aac719eb5",
		"startDate": "2024-11-02T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-10T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw7919d52d-86b9-4e7b-9ef7-28426b168aa2",
		"startDate": "2024-11-03T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-11T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw41f924ba-63d8-4c98-a6ac-a0e5ff5b1246",
		"startDate": "2024-11-04T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-12T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw5f1eefd9-cbed-45f0-b969-87fa6d4a83b2",
		"startDate": "2024-11-05T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-13T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwdfd63a52-b4d0-4b5b-a506-e59630650e3c",
		"startDate": "2024-11-06T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-14T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw99d0bfcd-743a-416f-890b-7682fd240a98",
		"startDate": "2024-11-07T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-15T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw04e73991-ce88-4be9-9820-30fb72cc51c4",
		"startDate": "2024-11-08T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-16T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwcf5cb67f-e74e-4651-9673-2a5da0675b76",
		"startDate": "2024-11-09T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-17T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwfb117d91-0a0f-41df-b313-097d329acf8d",
		"startDate": "2024-11-10T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-18T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw4b4c67d0-04ce-488c-bbbd-4ef8b214f44c",
		"startDate": "2024-11-11T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-19T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw169fcfbf-ac2b-4e92-95e7-742261c2b160",
		"startDate": "2024-11-12T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-20T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwb61dabf8-e796-44bd-ab9c-f8be1d19920c",
		"startDate": "2024-11-13T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-21T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwd7fabd9d-a0a1-424f-aefd-65d433c4eff4",
		"startDate": "2024-11-14T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-22T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw716d7125-9237-468b-b52a-f71725cab222",
		"startDate": "2024-11-15T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-23T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw2f7b8d48-337c-4723-99b2-53722fc3c749",
		"startDate": "2024-11-16T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-24T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw5583182a-b9ce-482f-ad1e-9ac5b4ad8dc9",
		"startDate": "2024-11-17T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-25T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw5f4c390d-797f-450a-b727-58bf73306b6b",
		"startDate": "2024-11-18T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-26T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw2a28f0e3-115d-433a-8454-219c02c9e0c1",
		"startDate": "2024-11-19T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-27T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwb174875d-d463-461c-91c4-67748929c403",
		"startDate": "2024-11-20T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-28T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwc4dadcf8-99c7-48b3-baa4-eeb54ca43c26",
		"startDate": "2024-11-21T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-29T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw28bcbd11-18e3-4f0d-a94f-3427c32448f7",
		"startDate": "2024-11-22T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-11-30T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw60df3429-88a5-49c7-90a4-a40ac3e38eb9",
		"startDate": "2024-11-23T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-01T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw8b572a70-cc6e-4e39-aae8-32f3b32c2c65",
		"startDate": "2024-11-24T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-02T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw9947cf26-86f3-497d-ac3e-758709045caa",
		"startDate": "2024-11-25T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-03T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw088c1af5-f3f7-4688-9395-255e131c0318",
		"startDate": "2024-11-26T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-04T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dweba53fd8-9171-4d78-8da3-65bfadfe85dd",
		"startDate": "2024-11-27T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-05T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwb5d2aca0-9b22-45eb-9d7e-4d153ed2ae2c",
		"startDate": "2024-11-28T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-06T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw04d38369-d459-4c42-a7ab-5fa104514de6",
		"startDate": "2024-11-29T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-07T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw4ea17a46-9acb-4b07-93b5-4e31ba8354b4",
		"startDate": "2024-11-30T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-08T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw16f6f975-2bc2-4774-b7ca-ae15aede4cb7",
		"startDate": "2024-12-01T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-09T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw10bcd91d-71b3-4ed3-b40c-94eee702b6d1",
		"startDate": "2024-12-02T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-10T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwb7fdb0ac-0da4-497d-8268-c12025b918ff",
		"startDate": "2024-12-03T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-11T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw9ff2c6f0-23fd-4cd4-a7f5-cf64acdb93cb",
		"startDate": "2024-12-04T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-12T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw20a585c8-6462-4a1c-8364-b2bab3f00963",
		"startDate": "2024-12-05T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-13T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dw65943e3b-17f8-4680-b5dc-2df58f5bacd3",
		"startDate": "2024-12-06T00:00Z"
	}, {
		"availabilityType": "AVAILABLE",
		"endDate": "2024-12-14T00:00Z",
		"validUntil": "2024-12-14T00:00Z",
		"deliveryWindowOptionId": "dwd5a4b613-debf-4523-b96a-31107636b3ab",
		"startDate": "2024-12-07T00:00Z"
	}]
}
```

**Comment by Christin519** [comment] 2024-10-28 01:43
@puppsupr I have provided all the requests and responses of one of my inbound plans.I hope this problem can be solved.

**Comment by ccyun06** [comment] 2024-10-28 09:28
@puppsupr me too

**Comment by Christin519** [comment] 2024-10-30 01:33
@puppsupr waiting for u

**Comment by puppsupr** [comment] 2024-10-31 20:41
Hi @Christin519 ,
Thanks for the details. Our team is looking into this. Will provide an update as soon as I hear back.

**Comment by Christin519** [comment] 2024-11-04 01:39
> Hi @Christin519 , Thanks for the details. Our team is looking into this. Will provide an update as soon as I hear back.

Is there any result?😊

**Comment by puppsupr** [comment] 2024-11-05 01:32
Hi @Christin519,
The window policy was reduced from 90 days to 45 days, so that's why you can't get more than 45 days on the delivery window.

**Comment by Christin519** [comment] 2024-11-05 01:37
> Hi @Christin519, The window policy was reduced from 90 days to 45 days, so that's why you can't get more than 45 days on the delivery window.


Is this also true for international shipments?

**Comment by Qusarber** [comment] 2024-12-03 11:05
Hello @Christin519. Have you found any possible solution for this so far? We are facing the same issue.
