### ISSUE TITLE
Finances API v2024-06-19 Reference `2024-06-19/transactions` -  nextToken page is broken

### ISSUE THREAD

**Issue by julioyildo** [amzn/selling-partner-api-models#4224] opened 2024-10-11 14:43 UTC
Hi,

Currently, I'm trying to catch data from `2024-10-07`  to `2024-10-09` on `A13V1IB3VIYZZH` (france) marketplaceID. The things is that when I'm requesting the nextToken page, I'm having the same response as the first one. And this result gives me a new nextToken which is returning the same page.

This looks like an infinite loop...

**Comment by julioyildo** [comment] 2024-10-11 15:28
Hi @jawheral,

Yes, I get this issue even by proving the same parameters values (`postedAfter`, `postedBefore` and `marketplaceId`)

Actually, I'm getting the data but not in the same order.

Best

**Comment by jawheral** [comment] 2024-10-11 15:35
Hi @julioyildo,

Sorry for the inconvenience. 
Could you please share the request ids? Both for an initial request (without nextToken) and a subsequent request (using nextToken) so we can better address this.

Thanks,
Jawher
Selling Partner Developer Services

**Comment by julioyildo** [comment] 2024-10-11 15:40
@jawheral

yep here they are : 
- init : 9668aaa9-fda1-452f-99f5-57e44021469c

- nextpage : 31e5ebbd-5de6-4a69-986e-ee78729362f5

Thanks you!

**Comment by jawheral** [comment] 2024-10-11 16:20
Thanks @julioyildo. 
There is no estimated time for a fix but our teams are aware and I will get back to you if I have any updates.

**Comment by susan828** [comment] 2024-10-14 03:23
I also encountered the same problem

**Comment by dengarcia** [comment] 2024-10-14 08:48
Hi there, I encountered the same problem with searchListingsItems pagination.
Is there anything we can do to help resolve this?

**Comment by dengarcia** [comment] 2024-10-14 09:00
I have the same issue with searchListingsItems pagination.
Let me know if there is anything I can do to help fix the issue or if you need more information.

**Comment by jawheral** [comment] 2024-10-15 07:38
Hi @julioyildo,

Could you please try again now and let us know if the issue is still there? 

Best,
Jawher
Selling Partner Developer Services

**Comment by julioyildo** [comment] 2024-10-15 12:45
Hi @jawheral,

Thank you for your response,

Actually, something strange is happening, I'm using Python with `requests.get(url, params=params, headers=headers, auth=auth)` method and when calling on `nextToken` (with other parameters) I'm getting this response: 

```
status_code=500 response={'errors': [{'code': 'InternalFailure', 'message': 'We encountered an internal error. Please try again.', 'details': ''}]}
```
Example with `nextToken`:  
- init `72527287-df16-41ba-a57a-ac86e774a5c4`
- nextToken : `5fbfa2d8-7896-4117-aebd-2f3f7ac72caa`


However, when I'm trying on `NextToken` (PascalCase, with other parameters), I'm retrieving data, but the issue is still present (getting only the first page, and infinite loop on nextToken).

Example with `NextToken`:
- init: `9e925071-852c-414b-911f-85835f2b342c`
- NextToken 1: `911f1d7a-fd02-44c6-a574-f33ef1ad6f79`
- NextToken 2: `47bd565b-8ff8-430d-a93c-a2d71c6c1dcb`
- NextToken 3: ...
- ...

Do you need any further information to resolve this?

Best

**Comment by jawheral** [comment] 2024-10-15 13:01
Hi @julioyildo,

Thank you for the quick feedback.
It would be nice if you provide me with the following information for each of the examples (nextToken and NextToken):
All parameters:
- postedAfter
- postedBefore
- marketplaceId
And
- sellerId
- requestId

Best,
Jawher
Selling Partner Developer Services

**Comment by gamestarxie** [comment] 2024-10-15 13:11
@jawheral 
Hello, I also have the same error. The first time I used the date parameter request, it could return 500 pieces of data and NextToken normally. The second time I used NextToken request, it would return a 500 error. Attached are my request response parameters. Could you please help me check the reason? Thank you


`--> GET https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER
x-amz-access-token: Atza|XXXX
Accept: application/json
x-amz-date: 20241015T130615Z
--> END GET
<-- 200 https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER (2865ms)
Server: Server
Date: Tue, 15 Oct 2024 13:06:18 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
x-amz-rid: X5DB7RP9PDCRXDYRE07Q
x-amzn-RateLimit-Limit: 0.5
x-amzn-RequestId: 57030df5-7ebe-4319-b96d-35121c76476d
x-amz-apigw-id: OPF57030df57ebe
X-Amzn-Trace-Id: Root=1-670e68ca-57030df57ebe4319
Vary: accept-encoding,Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
<-- END HTTP
--> GET https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?nextToken=AQICAHgLu0WbpD9cWyxMqnCwZdIPlpc4%252Fc1mq%252B4rX9fTcb5HgwExxDDbu90ihaxMBTNOwedZAAAFkTCCBY0GCSqGSIb3DQEHBqCCBX4wggV6AgEAMIIFcwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzHWCY12IupDo0StwQCARCAggVEdcHhShTk6b3u%252BDap2PIYX0UmCKNDOyYASMzA%252BCaefySnPvg27eo5ML%252FO48iI0F6dL%252FizyYfcGwF5mloDI%252FJ4lfpYo5WD25NreyMq7ILnWSiZPphjfr7EZw3OAmXJFr94MQDblyP%252BcfAKRqsIHok%252BwCTJQ5kPSIur%252BZo87ijLj5MZp9D3gTpI2BA6ocnbQ5uj9xNyVoAxikI%252B%252BH54um76HRPmGOg9eQVvA%252BE4qP2D96Z9EyR4KQZMC3l0fRIQELSkLnF37FgwHWKKQzEqB0VlXAjGTYVjVIz0A1VfZcr3UjM4NCAYcFHtjQyk7crthlTONc0yk5l2kHHTakayGb9EMW1raFcpNxyF9YThIZPdM0DL2PAC4P4E4D8v2X%252BTq3oPd3i2TyFAxLh1koJsw%252Fl9yAXb5W8FKHmCvSMc4k7Hh%252Bd7ZchfeFZJJb5bhVmDpgdhZju%252Be09YZZn47dzn91u0n0UDlrIgYr3lyXaVL0ZKp2liltoBjq7%252FSZvKGWCUDzhdDdf9JoEwzvW8oMXgN6yEEQb1n3g7W4H4e2cx3CkguXgA7R42U4h93O5HTRly3SQPCcXguW7LoS1q1wRLLIMKfFtM2nhQLjWvkXuIV%252FtUZscyiJhyfRQy03%252FbZiO%252FS2IIk%252BQyuGMUo1trn3GSlhTv6e3HwPI8T192ptnd3EvRb%252FymPf1iiSv22e3n1zfQd7ErLLZIGgQUdU%252BS73d9WHOVedhTEo2xtBLbA7HZRfmUtRrVJiaRNRDeZR8pqr93Z5oF30o6P9O4%252FfYt6qdXuxLPLQf1%252Bt%252BDI7e9I7ZmSfiPQIAcHgVb8wke3p5rowfhn7%252BhfO6JDP5oVc0431F6Iy%252FF1Eyz2T6sl2u0cYW%252FlZMVDNiYBuul853LyGNp99OSjm7%252Fv58XoWRssdhrqC8IzoEeAHiom9H1G58D42bZD8WJeUur66QzAtfEW0ZNzLRs94JjB8YHlb%252Bz81rKh221davAywSSkX%252Fquts9de%252BmkB1MfDUxFw89FTe18FDaZD0VtFAjxbfsAh02VCc%252FCPKpz4tChU9N8unbadCqI73p4NqrlyTuNfoIfzA8Hkodx1l0olsr9ChnvvWiBUvC3%252FmurytYulqW6W%252BCAJU59mYbaWBwGUCwT33nGCnn0MaENAdSgmuL%252Bkoxz3iQb%252FEiVz4zNDJfpW5Y1jGj2WorVvfdyykkwZ%252B%252FUdxmojN4wyYgxKhxjfZHHlJJPKUq9uYvvskMVPl%252FljZiIEEKrNphrfrn3N%252FE0EKND0nFsQvuY5h0wS34zjFjN1nNBYjOVd%252FSqAWA852nZfbk41kG3xOmKirMHrnupF66pk0uzj4gTDGmNRQq%252FmcVgfua6OpQhSMpnZn40Q6YmscZzfwg4RT4FYwkmUaf6vwte%252Bg2svJXY2bIpTkLVZA1hJfiCGMp%252BgSVxtqbIt3O8NnhLtNRfeiN2vZFV6rrCVC6g%252F6Ontu0p4%252BjextY87lxekU9dsM3OlEUsrJ6VGIpB7ljwKPoy80kVvN7jhzdibWx%252BSW6uSBN7aG2QpUwfHwQrU4SsyPaHvR3ezms0pAgNhyjKW1xCbpeelqwW%252FKPvr3gOtZp4SrIpmQ4RQGHz8wN2n83w8dq6bmbcoxJN1cInthkYf%252FoCZPRRsAhMzl4R8TQsRguxyzynzURuMZWEO2blynyEedOTbwrbLRAea1IN0HIpmEllNH7hpLe8zlJr9Q2XQ%252F3fOU%252BhyspZEAIJ1zr2XxYE56ysBp54D3sZgZHcFqcJjK%252FLW9lAYw2yPhrRp4%252BSBCK1Os2ZA6Y6ePhkZJgYTthfA%253D%253D
x-amz-access-token: Atza|XXXX
Accept: application/json
x-amz-date: 20241015T130621Z
--> END GET
<-- 500 https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?nextToken=AQICAHgLu0WbpD9cWyxMqnCwZdIPlpc4%252Fc1mq%252B4rX9fTcb5HgwExxDDbu90ihaxMBTNOwedZAAAFkTCCBY0GCSqGSIb3DQEHBqCCBX4wggV6AgEAMIIFcwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzHWCY12IupDo0StwQCARCAggVEdcHhShTk6b3u%252BDap2PIYX0UmCKNDOyYASMzA%252BCaefySnPvg27eo5ML%252FO48iI0F6dL%252FizyYfcGwF5mloDI%252FJ4lfpYo5WD25NreyMq7ILnWSiZPphjfr7EZw3OAmXJFr94MQDblyP%252BcfAKRqsIHok%252BwCTJQ5kPSIur%252BZo87ijLj5MZp9D3gTpI2BA6ocnbQ5uj9xNyVoAxikI%252B%252BH54um76HRPmGOg9eQVvA%252BE4qP2D96Z9EyR4KQZMC3l0fRIQELSkLnF37FgwHWKKQzEqB0VlXAjGTYVjVIz0A1VfZcr3UjM4NCAYcFHtjQyk7crthlTONc0yk5l2kHHTakayGb9EMW1raFcpNxyF9YThIZPdM0DL2PAC4P4E4D8v2X%252BTq3oPd3i2TyFAxLh1koJsw%252Fl9yAXb5W8FKHmCvSMc4k7Hh%252Bd7ZchfeFZJJb5bhVmDpgdhZju%252Be09YZZn47dzn91u0n0UDlrIgYr3lyXaVL0ZKp2liltoBjq7%252FSZvKGWCUDzhdDdf9JoEwzvW8oMXgN6yEEQb1n3g7W4H4e2cx3CkguXgA7R42U4h93O5HTRly3SQPCcXguW7LoS1q1wRLLIMKfFtM2nhQLjWvkXuIV%252FtUZscyiJhyfRQy03%252FbZiO%252FS2IIk%252BQyuGMUo1trn3GSlhTv6e3HwPI8T192ptnd3EvRb%252FymPf1iiSv22e3n1zfQd7ErLLZIGgQUdU%252BS73d9WHOVedhTEo2xtBLbA7HZRfmUtRrVJiaRNRDeZR8pqr93Z5oF30o6P9O4%252FfYt6qdXuxLPLQf1%252Bt%252BDI7e9I7ZmSfiPQIAcHgVb8wke3p5rowfhn7%252BhfO6JDP5oVc0431F6Iy%252FF1Eyz2T6sl2u0cYW%252FlZMVDNiYBuul853LyGNp99OSjm7%252Fv58XoWRssdhrqC8IzoEeAHiom9H1G58D42bZD8WJeUur66QzAtfEW0ZNzLRs94JjB8YHlb%252Bz81rKh221davAywSSkX%252Fquts9de%252BmkB1MfDUxFw89FTe18FDaZD0VtFAjxbfsAh02VCc%252FCPKpz4tChU9N8unbadCqI73p4NqrlyTuNfoIfzA8Hkodx1l0olsr9ChnvvWiBUvC3%252FmurytYulqW6W%252BCAJU59mYbaWBwGUCwT33nGCnn0MaENAdSgmuL%252Bkoxz3iQb%252FEiVz4zNDJfpW5Y1jGj2WorVvfdyykkwZ%252B%252FUdxmojN4wyYgxKhxjfZHHlJJPKUq9uYvvskMVPl%252FljZiIEEKrNphrfrn3N%252FE0EKND0nFsQvuY5h0wS34zjFjN1nNBYjOVd%252FSqAWA852nZfbk41kG3xOmKirMHrnupF66pk0uzj4gTDGmNRQq%252FmcVgfua6OpQhSMpnZn40Q6YmscZzfwg4RT4FYwkmUaf6vwte%252Bg2svJXY2bIpTkLVZA1hJfiCGMp%252BgSVxtqbIt3O8NnhLtNRfeiN2vZFV6rrCVC6g%252F6Ontu0p4%252BjextY87lxekU9dsM3OlEUsrJ6VGIpB7ljwKPoy80kVvN7jhzdibWx%252BSW6uSBN7aG2QpUwfHwQrU4SsyPaHvR3ezms0pAgNhyjKW1xCbpeelqwW%252FKPvr3gOtZp4SrIpmQ4RQGHz8wN2n83w8dq6bmbcoxJN1cInthkYf%252FoCZPRRsAhMzl4R8TQsRguxyzynzURuMZWEO2blynyEedOTbwrbLRAea1IN0HIpmEllNH7hpLe8zlJr9Q2XQ%252F3fOU%252BhyspZEAIJ1zr2XxYE56ysBp54D3sZgZHcFqcJjK%252FLW9lAYw2yPhrRp4%252BSBCK1Os2ZA6Y6ePhkZJgYTthfA%253D%253D (273ms)
Server: Server
Date: Tue, 15 Oct 2024 13:06:21 GMT
Content-Type: application/json
Content-Length: 158
Connection: keep-alive
x-amz-rid: M0F65Z97434FDJXK86S2
x-amzn-RequestId: db4292c8-96a7-48e7-9555-c3647db3b1be
x-amz-apigw-id: OPFdb4292c896a7
X-Amzn-Trace-Id: Root=1-670e68cd-db4292c896a748e7
Vary: Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
<-- END HTTP
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}`

**Comment by jawheral** [comment] 2024-10-15 13:16
Hi @gamestarxie
You should also provide the parameters from the initial request along with the `nextToken` in subsequent requests - `postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER&nextToken=...`

Please let me know if this solves the issue in your case.

**Comment by julioyildo** [comment] 2024-10-15 13:21
> Hi @julioyildo,
> 
> Thank you for the quick feedback. It would be nice if you provide me with the following information for each of the examples (nextToken and NextToken): All parameters:
> 
> * postedAfter
> * postedBefore
> * marketplaceId
>   And
> * sellerId
> * requestId
> 
> Best, Jawher Selling Partner Developer Services

Sure,


Parameters are the same for all requestIds I provided. 

SellerID: `A6CBTFH6MPQRA`

```python
params = {
    'postedAfter': '2024-10-07',
    'postedBefore': '2024-10-10',
    'marketplaceId': 'A13V1IB3VIYZZH'
}
``` 

Best

**Comment by gamestarxie** [comment] 2024-10-15 13:26
> Reference in new issue

Even if other parameters are attached, the error message remains the same


`
--> GET https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER
x-amz-access-token: Atza|XXXX
Accept: application/json
x-amz-date: 20241015T132204Z
--> END GET
<-- 200 https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER (2546ms)
Server: Server
Date: Tue, 15 Oct 2024 13:22:07 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
x-amz-rid: 5VSAKH7QXE25BF0YDWEG
x-amzn-RateLimit-Limit: 0.5
x-amzn-RequestId: 902aa02d-3213-4a22-8ed5-f89797455738
x-amz-apigw-id: OPF902aa02d3213
X-Amzn-Trace-Id: Root=1-670e6c7f-902aa02d32134a22
Vary: accept-encoding,Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
<-- END HTTP
--> GET https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER&nextToken=AQICAHgLu0WbpD9cWyxMqnCwZdIPlpc4%252Fc1mq%252B4rX9fTcb5HgwED%252FxaG2qccF26TPu8CSvdqAAAFkTCCBY0GCSqGSIb3DQEHBqCCBX4wggV6AgEAMIIFcwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx4oD%252FVPPXStxD2CJICARCAggVEhCJ7rPjY8CZxxN7DGxayykl6eb0dl3YA%252BFvKMU5XEuma2gtfHbSDlmkqqOZJQlVv2v8qXOmtLnIDTmcrLJowuGlXyWWv4LZMTmRN9JRy%252B2ubrEj%252FFUc%252F4MbjcaDnRR5ise%252BBVWulApFIK051YvZvAUp0atDNGWESCnW6niM9LS3MJ3RmVxA%252BtqwNgTRDe65xwO6Gj4cA9pjpTN1gFqPN7PINuynd7MR3XitR6Wza3yMnMmtdlj%252BxPVuUQt9jzRVvfKG5%252BjoEO%252BiRtJeseYcUTAlwO5m7ZR64K4AYxJ0QEXvDUjCL2frCqT3Y8lqYx7LA641KCRFVPMEfgM6V2RjRQMAaSh1FvcI5Vr1JtwhPR83uQbJGcrI1W6jd%252FwWZxl1YjDSxYJmz%252ByuAB27jXWxo81ZPVvI4I%252FXBxrfYhz1haE2FRThnNznIkZl%252BAdV3H0nqQde9mvQKAFl1s%252FK8wGDQzbcyqWdKUEdJwFF%252BNS2A3MS5hgTvpVa3eIbY9Z3l%252F7LNM565mXVp%252Bld4wLvbb9SkgGib1J1et0iGEEKXWOliUzzzCtIBVDBCpi0FlnSjGuwsXkAoCJ9T3POs9Up61jNkXolAXKCNFfHRFtsvNSaMATB%252FrhS1uLl3Ry0C9nZi%252B5adlavwV3DhVdJcWzdsGkmSEIIhlQoGqobsLW%252Bc9N5ZnXlJt0anfTnJtxO8nasQOU5LNAT1Uz9w2oEnXPgYK6o%252F78ZsYoDTEJz%252BmZo2F%252F1r56pZCrZ2Mwpma7LPltJODmzFt4JWeixmAuR42IWOOBqwBGdCcw0ne98CT2XiDw7TYSbHK4wpe8hCrdqLg5RdZ5OTO3vV7dGj89%252FyfxiIQocgudXI8QnJFH5ofMOl1yCZYyW0X9Fo98on4xdopR8DnQQTGaA6yIz8T%252BVjRV5WYHGakZhLvXzki47n6XSYy4OhC8NHFh5a5oRxQiDE%252Bt68%252FOwO7URqIU765%252BchSUqFEodziD6F3ParP6Vc4IUftU13hYDBg1D2UL5mLFHbTqB5aV4hjlcfr4%252FEMheM%252Fmebx9T%252Fbmuo16ZeDUoA6cYuyz7SdrptcbNMVtyIeStq%252B1RO3FNrVCjV85%252BJKp9Uu4GGmdzJOipW7z5VILE4zCGntHCEU9LxB72t66lFOYST%252BIfR4BPzZ3alhFTU5jvxKVuOO5Hia766hiOAxexfc7%252BsPEtMgUCFkweB92j%252BWJ29GU1h7XeGX9kpBUCc%252B7%252Fw6AcN4SYXep42mALUL4IycMrLIyOtkE0NVUIcC8PphPdSgySNN2mXMRTpIqnVkcXP0NFKz%252Bfr6LVmlL0uCHpc5Q%252FR%252BcFqb%252FOESp1h1z78Opy85384GotYjVGg0Lot0axZ1fOWaYKf9goJ1byghZp3xJodwWPmUWaavZK%252BVWfAMx9tAw9e6nnlTrILmcrcKF58rF0dIVuxHDhQFCmOkLcByfd6EiwSDjZKGBSGuKWb6kMrsjdtVcx55DgVMb8IIj9KgfFBjQaw5%252BoU52H5ZFdausDZppYyeRkHX%252FKHItBchlBiIHfe%252B70nvjnmtxGZ%252FVA1tZvMbLnA%252BoQijQZkGmfG9FTxP76Ro68TQtatyplin%252F65TGWYVJUtGg7rNsPO%252B3ytVtQDcI%252Bm1LM89yNCZUMPeBtfrk3KueuUXPUhY8S0k6xT4KPF92DyXeu%252FJBLPHRIXmklxxcNCBF4VDo5Ih7Vt%252FDxSaEF3Az0ZNyLLJobm6qBh3B5h533I3XmODCfxv7umdnFIgszd4v0kvYOQxFcLdN%252B%252F3oC2%252F2Gv4rb6DX9dhdzP7BY3zOmfM7SCfQ%253D%253D
x-amz-access-token: Atza|XXXX
Accept: application/json
x-amz-date: 20241015T132218Z
--> END GET
<-- 500 https://sellingpartnerapi-na.amazon.com/finances/2024-06-19/transactions?postedAfter=2024-10-01T00%3A00%3A00Z&postedBefore=2024-10-15T00%3A00%3A00Z&marketplaceId=ATVPDKIKX0DER&nextToken=AQICAHgLu0WbpD9cWyxMqnCwZdIPlpc4%252Fc1mq%252B4rX9fTcb5HgwED%252FxaG2qccF26TPu8CSvdqAAAFkTCCBY0GCSqGSIb3DQEHBqCCBX4wggV6AgEAMIIFcwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx4oD%252FVPPXStxD2CJICARCAggVEhCJ7rPjY8CZxxN7DGxayykl6eb0dl3YA%252BFvKMU5XEuma2gtfHbSDlmkqqOZJQlVv2v8qXOmtLnIDTmcrLJowuGlXyWWv4LZMTmRN9JRy%252B2ubrEj%252FFUc%252F4MbjcaDnRR5ise%252BBVWulApFIK051YvZvAUp0atDNGWESCnW6niM9LS3MJ3RmVxA%252BtqwNgTRDe65xwO6Gj4cA9pjpTN1gFqPN7PINuynd7MR3XitR6Wza3yMnMmtdlj%252BxPVuUQt9jzRVvfKG5%252BjoEO%252BiRtJeseYcUTAlwO5m7ZR64K4AYxJ0QEXvDUjCL2frCqT3Y8lqYx7LA641KCRFVPMEfgM6V2RjRQMAaSh1FvcI5Vr1JtwhPR83uQbJGcrI1W6jd%252FwWZxl1YjDSxYJmz%252ByuAB27jXWxo81ZPVvI4I%252FXBxrfYhz1haE2FRThnNznIkZl%252BAdV3H0nqQde9mvQKAFl1s%252FK8wGDQzbcyqWdKUEdJwFF%252BNS2A3MS5hgTvpVa3eIbY9Z3l%252F7LNM565mXVp%252Bld4wLvbb9SkgGib1J1et0iGEEKXWOliUzzzCtIBVDBCpi0FlnSjGuwsXkAoCJ9T3POs9Up61jNkXolAXKCNFfHRFtsvNSaMATB%252FrhS1uLl3Ry0C9nZi%252B5adlavwV3DhVdJcWzdsGkmSEIIhlQoGqobsLW%252Bc9N5ZnXlJt0anfTnJtxO8nasQOU5LNAT1Uz9w2oEnXPgYK6o%252F78ZsYoDTEJz%252BmZo2F%252F1r56pZCrZ2Mwpma7LPltJODmzFt4JWeixmAuR42IWOOBqwBGdCcw0ne98CT2XiDw7TYSbHK4wpe8hCrdqLg5RdZ5OTO3vV7dGj89%252FyfxiIQocgudXI8QnJFH5ofMOl1yCZYyW0X9Fo98on4xdopR8DnQQTGaA6yIz8T%252BVjRV5WYHGakZhLvXzki47n6XSYy4OhC8NHFh5a5oRxQiDE%252Bt68%252FOwO7URqIU765%252BchSUqFEodziD6F3ParP6Vc4IUftU13hYDBg1D2UL5mLFHbTqB5aV4hjlcfr4%252FEMheM%252Fmebx9T%252Fbmuo16ZeDUoA6cYuyz7SdrptcbNMVtyIeStq%252B1RO3FNrVCjV85%252BJKp9Uu4GGmdzJOipW7z5VILE4zCGntHCEU9LxB72t66lFOYST%252BIfR4BPzZ3alhFTU5jvxKVuOO5Hia766hiOAxexfc7%252BsPEtMgUCFkweB92j%252BWJ29GU1h7XeGX9kpBUCc%252B7%252Fw6AcN4SYXep42mALUL4IycMrLIyOtkE0NVUIcC8PphPdSgySNN2mXMRTpIqnVkcXP0NFKz%252Bfr6LVmlL0uCHpc5Q%252FR%252BcFqb%252FOESp1h1z78Opy85384GotYjVGg0Lot0axZ1fOWaYKf9goJ1byghZp3xJodwWPmUWaavZK%252BVWfAMx9tAw9e6nnlTrILmcrcKF58rF0dIVuxHDhQFCmOkLcByfd6EiwSDjZKGBSGuKWb6kMrsjdtVcx55DgVMb8IIj9KgfFBjQaw5%252BoU52H5ZFdausDZppYyeRkHX%252FKHItBchlBiIHfe%252B70nvjnmtxGZ%252FVA1tZvMbLnA%252BoQijQZkGmfG9FTxP76Ro68TQtatyplin%252F65TGWYVJUtGg7rNsPO%252B3ytVtQDcI%252Bm1LM89yNCZUMPeBtfrk3KueuUXPUhY8S0k6xT4KPF92DyXeu%252FJBLPHRIXmklxxcNCBF4VDo5Ih7Vt%252FDxSaEF3Az0ZNyLLJobm6qBh3B5h533I3XmODCfxv7umdnFIgszd4v0kvYOQxFcLdN%252B%252F3oC2%252F2Gv4rb6DX9dhdzP7BY3zOmfM7SCfQ%253D%253D (742ms)
Server: Server
Date: Tue, 15 Oct 2024 13:22:19 GMT
Content-Type: application/json
Content-Length: 158
Connection: keep-alive
x-amz-rid: QD1Y6V36GZ8CBJR533GJ
x-amzn-RequestId: caa8294e-71c2-4421-a3b1-bfccd5c20c59
x-amz-apigw-id: OPFcaa8294e71c2
X-Amzn-Trace-Id: Root=1-670e6c8b-caa8294e71c24421
Vary: Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
<-- END HTTP
{
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}
`

**Comment by jawheral** [comment] 2024-10-15 13:44
Thank you all for providing the details! 
Our teams are aware and I will get in touch once I receive any new updates.

Best,
Jawher
Selling Partner Developer Services

**Comment by dengarcia** [comment] 2024-10-15 17:07
To clarify, and to ensure you are aware of it, I am having similar issues with 'ListingsItemsApi / searchListingsItems'

**Comment by weilinggu** [comment] 2024-10-15 19:34
@dengarcia Thanks for letting us know. We are currently working on a fix for 'ListingsItemsApi / searchListingsItems'. I will keep you updated once the issue is fixed.

Weiling
Selling Partner Developer Services

**Comment by jawheral** [comment] 2024-10-16 10:37
Hi @gamestarxie,

Could you please also provide the sellerId? 
Thank you

**Comment by gamestarxie** [comment] 2024-10-16 13:57
@jawheral 

A1R2N6LO0SJPHW

May I ask when it can be resolved?

**Comment by jawheral** [comment] 2024-10-16 16:49
Hi @julioyildo,

The issue for the loop/redundant transactions should be fixed by now. Please try it and let me know.
Regarding the internal server error (@gamestarxie also), I don't have news yet. I will get write here once I have any updates.

Best,
Jawher
Selling Partner Developer Services

**Comment by julioyildo** [comment] 2024-10-17 13:20
Hi @jawheral,

Thank you for the quick return,

I will test it and let you know.

Best

**Comment by jawheral** [comment] 2024-10-21 07:20
Hi @gamestarxie,

Our teams confirmed that the `nextToken` returned in the response is already encoded while yours are being encoded again. Please make sure to provide the token as you receive it from the API.

Kindly confirm fixes for both issues.

Best,
Jawher
Selling Partner Developer Services

**Comment by julioyildo** [comment] 2024-10-21 15:25
Hi @jawheral,

`nextToken` seems to be working well on my side. 

How about to others ? @susan828 @dengarcia @gamestarxie 

Thank you!

Best

**Closed** 2024-10-22 20:03 UTC

**Comment by weilinggu** [comment] 2024-10-29 20:43
@dengarcia try encoding your page token before using it on your second call for 'ListingsItemsApi / searchListingsItems' and see if that fixed it

Thanks
Weiling
Selling Partner Developer Services

**Comment by gamestarxie** [comment] 2024-11-01 02:36
@jawheral 

> Hi @julioyildo,
> 
> The issue for the loop/redundant transactions should be fixed by now. Please try it and let me know. Regarding the internal server error (@gamestarxie also), I don't have news yet. I will write here once I have any updates.
> 
> Best, Jawher Selling Partner Developer Services

@jawheral 
Hello, you replied to me last time saying that it has been fixed, and indeed this error has not been reported again. However, since yesterday afternoon, I have been reporting this error again without modifying the code. Unlike before, this error was reported every time I used NextToken to query, but now it is reported irregularly during the query process

**Comment by kwedaras** [comment] 2024-12-23 20:24
Hello,
I am having the same issue with: 2024-06-19/transactions
I make first request - get the data (500 transactions and a next_token). I use that token to get the next 500 transactions, but I get the almost the same data. (i should have 1000 unique transactions, but have 890). 
Subsequent calls repeat data in the 2nd call (after 6 calls i have 890 unique transactions). I am changing next_token on every call of course.
