### ISSUE TITLE
Issue with confirmTransportationOptions on inboud shipment.

### ISSUE THREAD

**Issue by hellokids86** [amzn/selling-partner-api-models#4162] opened 2024-09-08 15:53 UTC
Hello,  
I am trying to confirm transport options on an inbound shipment via the API. I receive the following error back after checking the operation status. It works on and off depending on the options I choose when confirming transportation. Not sure what is wrong with my request.

{
"operation": "confirmTransportationOptions",
"operationId": "a41cc4e8-9235-4472-b832-3d3931cedcf6",
"operationProblems": [
{
"code": "BadRequest",
"message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors.",
"severity": "ERROR"
}
],
"operationStatus": "FAILED"
}

**Comment by hellokids86** [comment] 2024-09-09 00:26
The issue seems to be with confirming Amazon Partnered LTL with confirmTransportationOptions .

**Comment by xyloneX** [comment] 2024-09-09 06:44
> The issue seems to be with confirming Amazon Partnered LTL with confirmTransportationOptions .

SPD Not support？

**Comment by hellokids86** [comment] 2024-09-09 19:41
Is SPD for Small Parcel? If so, this is working, however LTL by Amazon Partnered Carriers is not working.

**Comment by xyloneX** [comment] 2024-09-10 03:04
I issue encountered this problem, just recreate it

**Comment by jackmin-sw** [comment] 2024-09-10 07:28
the same issue, just return ERROR: Fail to execute CONFIRM_CARRIERS API with errors, the api works well before today.

**Comment by emakunin** [comment] 2024-09-10 09:26
+1 it seems to be a duplicate of https://github.com/amzn/selling-partner-api-models/issues/4048

I use SPD shipments, details are in the linked ticket.

**Comment by puppsupr** [comment] 2024-09-11 06:04
#4048 Tracking it via the linked thread. Please provide full request and response in that thread.

**Closed by puppsupr** 2024-09-11 06:04 UTC

**Comment by johnkw** [comment] 2024-10-29 17:46
See also bug #4253 which notes the only current workaround is delete everything and retry.
